// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { cleanup, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import OwnInfraPanel from './OwnInfraPanel'
import type { OwnInfrastructure } from '../lib/types'

afterEach(() => cleanup())

// jsdom doesn't implement these — the component's download/copy actions need real stand-ins so
// clicking those buttons doesn't throw, without asserting anything about a real browser download.
beforeEach(() => {
  vi.stubGlobal('URL', { ...URL, createObjectURL: vi.fn(() => 'blob:mock'), revokeObjectURL: vi.fn() })
  Object.defineProperty(navigator, 'clipboard', {
    value: { writeText: vi.fn().mockResolvedValue(undefined) },
    configurable: true,
  })
  // jsdom doesn't implement blob-URL navigation — the download button sets an <a href> and clicks
  // it, which jsdom otherwise logs as an unimplemented "navigation" error.
  HTMLAnchorElement.prototype.click = vi.fn()
})

function baseOwn(overrides: Partial<OwnInfrastructure> = {}): OwnInfrastructure {
  return {
    regions: [{ region: 'us-east-1', resourceCount: 1, evidence: ['main.tf:1'] }],
    findings: [],
    unresolved: [],
    filesScanned: 1,
    fixes: [],
    fixesPrText: null,
    ...overrides,
  }
}

describe('OwnInfraPanel', () => {
  it('renders nothing when own is null', () => {
    const { container } = render(<OwnInfraPanel own={null} />)
    expect(container).toBeEmptyDOMElement()
  })

  it('shows a "Suggested fixes" section with a diff for a patched fix', async () => {
    const own = baseOwn({
      findings: [
        {
          rule: 'RDS_SINGLE_AZ',
          severity: 'high',
          pillar: 'Reliability',
          resource: 'aws_db_instance.primary',
          file: 'main.tf',
          line: 2,
          message: 'No Multi-AZ.',
          fixSnippet: 'multi_az = true',
        },
      ],
      fixes: [
        {
          rule: 'RDS_SINGLE_AZ',
          resource: 'aws_db_instance.primary',
          file: 'main.tf',
          status: 'patched',
          diff: '--- a/main.tf\n+++ b/main.tf\n@@ -1,3 +1,3 @@\n-  multi_az = false\n+  multi_az = true\n',
          prText: '### fix',
        },
      ],
      fixesPrText: '## PR body\n\n*generated by Blast Radius Mapper: review before merging*',
    })

    render(<OwnInfraPanel own={own} />)

    // Toolbar-level combined PR command is visible without expanding anything.
    expect(screen.getByRole('button', { name: /copy gh pr create --draft/i })).toBeInTheDocument()

    await userEvent.click(screen.getByText('Suggested fixes'))
    expect(screen.getByText('Suggested fix ready')).toBeInTheDocument()
    expect(screen.getByText(/^\+\s*multi_az = true$/)).toBeInTheDocument()

    await userEvent.click(screen.getByRole('button', { name: /download \.patch/i }))
    expect(URL.createObjectURL).toHaveBeenCalled()

    // user-event installs its own clipboard stub, so assert the user-visible feedback (which only
    // appears once the real writeText() call resolves) rather than spying on the function directly.
    await userEvent.click(screen.getByRole('button', { name: /copy git apply command/i }))
    expect(await screen.findByText('Copied')).toBeInTheDocument()
  })

  it('shows the refusal reason inline for a refused fix, with no diff controls', async () => {
    const own = baseOwn({
      findings: [
        {
          rule: 'RDS_SINGLE_AZ',
          severity: 'high',
          pillar: 'Reliability',
          resource: 'aws_db_instance.primary',
          file: 'main.tf',
          line: 2,
          message: 'No Multi-AZ.',
          fixSnippet: 'multi_az = true',
        },
      ],
      fixes: [
        {
          rule: 'RDS_SINGLE_AZ',
          resource: 'aws_db_instance.primary',
          file: 'main.tf',
          status: 'refused',
          note: 'Resource block contains a dynamic "..." block — a text-only patch cannot safely edit inside it; review manually.',
        },
      ],
    })

    render(<OwnInfraPanel own={own} />)
    await userEvent.click(screen.getByText('Suggested fixes'))
    expect(screen.getByText('No patch generated')).toBeInTheDocument()
    expect(screen.getByText(/dynamic "\.\.\." block/)).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /download \.patch/i })).not.toBeInTheDocument()
  })

  it('does not show the combined PR command toolbar when nothing was patched', () => {
    const own = baseOwn({
      findings: [
        {
          rule: 'SINGLE_REGION',
          severity: 'medium',
          pillar: 'Reliability',
          resource: 'provider region (us-east-1)',
          file: 'main.tf',
          line: 1,
          message: 'Single region.',
          fixSnippet: '# add a DR provider alias',
        },
      ],
      fixes: [{ rule: 'SINGLE_REGION', resource: 'provider region (us-east-1)', file: 'main.tf', status: 'advisory', note: 'Architectural.' }],
    })

    render(<OwnInfraPanel own={own} />)
    expect(screen.queryByRole('button', { name: /copy gh pr create --draft/i })).not.toBeInTheDocument()
  })
})
