// Fix generator for Prompt 15's ("Your infrastructure") own-infra findings — deterministic,
// mechanical text patches for R2/R3/R4/R6 in Terraform, plus PR text. R1 (SINGLE_REGION) and R5
// (SINGLE_INSTANCE) are architectural: advisory text only, never a patch. CFN/SAM findings are
// always refused too — Prompt 15 has no CFN/SAM parser (cut under that task's own time-box
// fallback), so a CFN patch could never be self-checked by re-running the linter; shipping one
// anyway would be exactly the kind of unverified fix "precision first" forbids.
//
// PATCHES ARE TEXT EDITS, NEVER A RE-PARSE + RE-SERIALIZE: every edit is a surgical splice inside
// the resource block's ORIGINAL source text (located via ownInfraTerraform's brace matching), so
// comments, `!Ref`/`!Sub`-style tags (irrelevant here since CFN is refused, but the same principle
// applies to any future format), and everything else outside the touched span survive byte-for-byte.
//
// SELF-CHECK: every candidate patch is applied in memory and the whole file set is re-linted
// (evaluateOwnInfrastructure) before being accepted — the target finding must disappear and no new
// finding may appear in that file, or the patch is dropped (recorded as 'refused', not silently
// hidden).

import { createTwoFilesPatch } from 'diff'
import { evaluateOwnInfrastructure } from '../../src/engine/ownInfrastructure'
import type { AttrValue, MultiRegionEvidence, ParsedResource, RegionEvidence } from '../../src/engine/ownInfrastructure'
import type { OwnInfraFinding, OwnInfraFixStatus, OwnInfraFixSuggestion, OwnInfraRuleId, OwnInfrastructure } from '../../src/lib/types'
import { findMatchingBrace, locateAttrValueSpan, locateResourceBlock, parseTerraformForOwnInfra, parseTfvars, type ResourceBlockLocation } from './ownInfraTerraform'

export interface OwnInfraDiscoveryFile {
  path: string
  content: string
}

const PATCHABLE_RULES: OwnInfraRuleId[] = ['RDS_SINGLE_AZ', 'DB_BACKUPS_DISABLED', 'DDB_NO_PITR', 'CACHE_NO_FAILOVER']

const ARCHITECTURAL_NOTE: Record<string, string> = {
  SINGLE_REGION:
    'Architectural — real multi-region redundancy (a DR region/provider alias, failover or latency routing, cross-region replication, a global table/cluster) is a design decision, not a mechanical one-line fix. No patch generated.',
  SINGLE_INSTANCE:
    'Architectural — moving off a single instance (ASG min/max, ECS desired count, or replacing a standalone EC2 instance with an Auto Scaling group) changes how the service is provisioned. No patch generated.',
}

// --- Exact-wording cost/risk notes (task spec: use this wording verbatim, never invented numbers) --

const NOTE_MULTI_AZ = 'Multi-AZ runs a standby replica and typically costs about double the single-AZ instance price; check current pricing.'
const NOTE_PITR = 'PITR adds continuous-backup storage cost.'
const NOTE_INTERRUPTION = 'Enabling backups or changing multi_az can cause a brief interruption or resource change; run terraform plan first.'
const NOTE_FAILOVER = 'Failover requires at least one replica, which adds cost.'

const COST_RISK_NOTE: Record<'RDS_SINGLE_AZ' | 'DB_BACKUPS_DISABLED' | 'DDB_NO_PITR' | 'CACHE_NO_FAILOVER', string> = {
  RDS_SINGLE_AZ: `${NOTE_MULTI_AZ} ${NOTE_INTERRUPTION}`,
  DB_BACKUPS_DISABLED: NOTE_INTERRUPTION,
  DDB_NO_PITR: NOTE_PITR,
  CACHE_NO_FAILOVER: NOTE_FAILOVER,
}

const WHAT_CHANGED: Record<'RDS_SINGLE_AZ' | 'DB_BACKUPS_DISABLED' | 'DDB_NO_PITR' | 'CACHE_NO_FAILOVER', string> = {
  RDS_SINGLE_AZ: 'Set `multi_az = true`.',
  DB_BACKUPS_DISABLED: 'Changed `backup_retention_period` from `0` to `7`.',
  DDB_NO_PITR: 'Enabled point-in-time recovery (`point_in_time_recovery { enabled = true }`).',
  CACHE_NO_FAILOVER: 'Set `automatic_failover_enabled = true`.',
}

const PR_FOOTER = '*generated by Blast Radius Mapper: review before merging*'

type PatchAttempt = { status: 'ok'; patchedContent: string } | { status: 'refused' | 'advisory'; reason: string }

function isTerraformFile(path: string): boolean {
  return path.endsWith('.tf')
}

function isTfvarsFile(path: string): boolean {
  return path.endsWith('.tfvars')
}

function mergeTfvars(files: OwnInfraDiscoveryFile[]): Record<string, AttrValue> {
  const tfvars: Record<string, AttrValue> = {}
  for (const f of files) if (isTfvarsFile(f.path)) Object.assign(tfvars, parseTfvars(f.content))
  return tfvars
}

/** Splits a finding's "type.name" resource address — Terraform types/names never contain '.'. */
function splitResourceAddress(resource: string): { type: string; name: string } {
  const dot = resource.indexOf('.')
  return { type: resource.slice(0, dot), name: resource.slice(dot + 1) }
}

function headerIndent(source: string, headerStart: number): string {
  const lineStart = source.lastIndexOf('\n', headerStart - 1) + 1
  return source.slice(lineStart, headerStart).match(/^\s*/)?.[0] ?? ''
}

/** Sets an existing top-level attribute's value (in place, preserving anything else on that line —
 * e.g. an inline comment) or inserts a new `key = value` line right after the block's `{` when the
 * attribute is absent entirely. */
function setOrInsertAttr(source: string, block: ResourceBlockLocation, nativeKey: string, literalText: string): PatchAttempt {
  const span = locateAttrValueSpan(block.neutralizedBlock, block.originalBlock, nativeKey)
  if (span) {
    const absStart = block.openIndex + span.start
    const absEnd = block.openIndex + span.end
    return { status: 'ok', patchedContent: source.slice(0, absStart) + literalText + source.slice(absEnd) }
  }
  const indent = `${headerIndent(source, block.headerStart)}  `
  const insertAt = block.openIndex + 1
  return { status: 'ok', patchedContent: `${source.slice(0, insertAt)}\n${indent}${nativeKey} = ${literalText}${source.slice(insertAt)}` }
}

/** DynamoDB PITR is a nested block, not a top-level attribute — three cases: no nested block at
 * all, a nested block with no `enabled` attr inside it, or a nested block with `enabled = false`. */
function setDynamoPitr(source: string, block: ResourceBlockLocation): PatchAttempt {
  const indent = `${headerIndent(source, block.headerStart)}  `
  const nestedMatch = /\bpoint_in_time_recovery\s*\{/.exec(block.neutralizedBlock)
  if (!nestedMatch) {
    const insertAt = block.openIndex + 1
    const insertText = `\n${indent}point_in_time_recovery {\n${indent}  enabled = true\n${indent}}`
    return { status: 'ok', patchedContent: `${source.slice(0, insertAt)}${insertText}${source.slice(insertAt)}` }
  }
  const nestedOpenRel = nestedMatch.index + nestedMatch[0].length - 1
  const nestedCloseRel = findMatchingBrace(block.neutralizedBlock, nestedOpenRel)
  const nestedNeutralized = block.neutralizedBlock.slice(nestedOpenRel, nestedCloseRel + 1)
  const nestedOriginal = block.originalBlock.slice(nestedOpenRel, nestedCloseRel + 1)
  const enabledSpan = locateAttrValueSpan(nestedNeutralized, nestedOriginal, 'enabled')
  if (enabledSpan) {
    const absStart = block.openIndex + nestedOpenRel + enabledSpan.start
    const absEnd = block.openIndex + nestedOpenRel + enabledSpan.end
    return { status: 'ok', patchedContent: source.slice(0, absStart) + 'true' + source.slice(absEnd) }
  }
  const nestedOpenAbs = block.openIndex + nestedOpenRel
  const insertAt = nestedOpenAbs + 1
  return { status: 'ok', patchedContent: `${source.slice(0, insertAt)}\n${indent}  enabled = true${source.slice(insertAt)}` }
}

function hasStaticReplicaEvidence(v: AttrValue | undefined): boolean {
  return v?.kind === 'literal' && typeof v.value === 'number' && v.value >= 2
}

/** Refusal conditions common to every rule — checked before any per-rule edit is attempted. */
function checkCommonRefusals(finding: OwnInfraFinding, block: ResourceBlockLocation): string | null {
  if (/(^|\/)modules\//.test(finding.file)) {
    return 'Resource is defined under a modules/ path — editing a shared Terraform module could affect every caller of it; review manually.'
  }
  if (/\bdynamic\s+"/.test(block.commentsBlankedBlock)) {
    return 'Resource block contains a dynamic "..." block — a text-only patch cannot safely edit inside it; review manually.'
  }
  if (/\bcount\s*=/.test(block.neutralizedBlock) || /\bfor_each\s*=/.test(block.neutralizedBlock)) {
    return 'Resource uses count/for_each (multiple instances) — a single text edit could apply incorrectly across instances; review manually.'
  }
  return null
}

function attemptPatch(current: string, finding: OwnInfraFinding, tfvars: Record<string, AttrValue>): PatchAttempt {
  const { type, name } = splitResourceAddress(finding.resource)
  const parsed = parseTerraformForOwnInfra(finding.file, current, tfvars)
  const resource = parsed.resources.find((r) => r.type === type && r.name === name)
  if (!resource) {
    return { status: 'refused', reason: 'Resource no longer found in this file — it may have been renamed or removed since the finding was computed.' }
  }
  const block = locateResourceBlock(current, type, name)
  if (!block) {
    return { status: 'refused', reason: 'Could not re-locate the resource block\'s exact text span — refusing rather than guessing.' }
  }
  const commonRefusal = checkCommonRefusals(finding, block)
  if (commonRefusal) return { status: 'refused', reason: commonRefusal }

  switch (finding.rule) {
    case 'RDS_SINGLE_AZ': {
      const existing = resource.attrs.multiAz
      if (existing?.kind === 'unresolved') return { status: 'refused', reason: existing.reason }
      return setOrInsertAttr(current, block, 'multi_az', 'true')
    }
    case 'DB_BACKUPS_DISABLED': {
      const existing = resource.attrs.backupRetentionPeriod
      if (existing?.kind === 'unresolved') return { status: 'refused', reason: existing.reason }
      if (!existing || existing.kind !== 'literal' || existing.value !== 0) {
        return { status: 'refused', reason: 'backup_retention_period is not an explicit 0 in this file anymore — nothing to patch.' }
      }
      return setOrInsertAttr(current, block, 'backup_retention_period', '7')
    }
    case 'DDB_NO_PITR': {
      const existing = resource.attrs.pointInTimeRecoveryEnabled
      if (existing?.kind === 'unresolved') return { status: 'refused', reason: existing.reason }
      return setDynamoPitr(current, block)
    }
    case 'CACHE_NO_FAILOVER': {
      const existing = resource.attrs.automaticFailoverEnabled
      if (existing?.kind === 'unresolved') return { status: 'refused', reason: existing.reason }
      const hasReplica = hasStaticReplicaEvidence(resource.attrs.numCacheClusters) || hasStaticReplicaEvidence(resource.attrs.replicasPerNodeGroup)
      if (!hasReplica) {
        return {
          status: 'advisory',
          reason:
            'No static evidence of >=2 cache clusters/replicas (num_cache_clusters or replicas_per_node_group) — automatic failover needs a replica to fail over to. Add one, then enable automatic_failover_enabled. Advisory only, no patch generated.',
        }
      }
      return setOrInsertAttr(current, block, 'automatic_failover_enabled', 'true')
    }
    default:
      return { status: 'refused', reason: `Rule ${finding.rule} is not in scope for the fix generator.` }
  }
}

/** Re-derives the Terraform-only lint result for a candidate file set — duplicates the small
 * tf-file-merge loop from server/src/ownInfra.ts's buildOwnInfrastructure (rather than importing
 * it) specifically to avoid a circular import: ownInfra.ts's own `own` field will eventually
 * include these very fixes, which are computed BY calling back into a lint of the patched files. */
function lintTerraformFiles(tfFiles: Map<string, string>, tfvars: Record<string, AttrValue>): OwnInfrastructure {
  const resources: ParsedResource[] = []
  const regionEvidence: RegionEvidence[] = []
  const multiRegionEvidence: MultiRegionEvidence[] = []
  for (const [path, content] of tfFiles) {
    const parsed = parseTerraformForOwnInfra(path, content, tfvars)
    resources.push(...parsed.resources)
    regionEvidence.push(...parsed.regionEvidence)
    multiRegionEvidence.push(...parsed.multiRegionEvidence)
  }
  return evaluateOwnInfrastructure(resources, regionEvidence, multiRegionEvidence, tfFiles.size)
}

function findingSignature(f: OwnInfraFinding): string {
  return `${f.rule}::${f.resource}`
}

/** Applies `candidateContent` (and separately `previousContent`) for `targetFile` on top of every
 * OTHER file's untouched original content, re-lints both, and confirms the target finding is gone
 * from AFTER and nothing new appeared in that file between BEFORE and AFTER. */
function selfCheck(
  targetFile: string,
  candidateContent: string,
  previousContent: string,
  otherFiles: Map<string, string>,
  tfvars: Record<string, AttrValue>,
  finding: OwnInfraFinding,
): { ok: true } | { ok: false; reason: string } {
  const before = lintTerraformFiles(new Map([...otherFiles, [targetFile, previousContent]]), tfvars)
  const after = lintTerraformFiles(new Map([...otherFiles, [targetFile, candidateContent]]), tfvars)

  const beforeSigs = new Set(before.findings.filter((f) => f.file === targetFile).map(findingSignature))
  const afterSigs = new Set(after.findings.filter((f) => f.file === targetFile).map(findingSignature))

  if (afterSigs.has(findingSignature(finding))) {
    return { ok: false, reason: 'Self-check failed: the target finding is still present after the patch was applied — dropped rather than shipping an unverified fix.' }
  }
  const newSigs = [...afterSigs].filter((s) => !beforeSigs.has(s))
  if (newSigs.length > 0) {
    return { ok: false, reason: `Self-check failed: applying this patch introduced a new finding (${newSigs.join(', ')}) — dropped rather than shipping a regression.` }
  }
  return { ok: true }
}

function buildFixPrSection(finding: OwnInfraFinding): string {
  const rule = finding.rule as keyof typeof WHAT_CHANGED
  return [
    `### ${finding.resource} — ${finding.rule} (${finding.file}:${finding.line})`,
    '',
    `**What changed:** ${WHAT_CHANGED[rule]}`,
    `**Why:** ${finding.message} (Well-Architected Reliability pillar.)`,
    `**Cost/risk:** ${COST_RISK_NOTE[rule]}`,
  ].join('\n')
}

/** Combined PR body for every 'patched' entry — or null when there's nothing to combine. */
export function buildFixesPrText(suggestions: OwnInfraFixSuggestion[]): string | null {
  const patched = suggestions.filter((s): s is OwnInfraFixSuggestion & { prText: string } => s.status === 'patched' && Boolean(s.prText))
  if (patched.length === 0) return null
  const intro =
    `## Reliability fixes from Blast Radius Mapper\n\n` +
    `This PR applies ${patched.length} deterministic, mechanical fix${patched.length === 1 ? '' : 'es'} from the ` +
    `"Your infrastructure" static IaC linter (Well-Architected Reliability pillar). Each change was self-checked: ` +
    `the finding it addresses was confirmed to disappear, and the linter was re-run to confirm no new finding appeared.`
  const sections = patched.map((s) => s.prText).join('\n\n')
  return `${intro}\n\n${sections}\n\n---\n\n${PR_FOOTER}`
}

/** Generates deterministic patch suggestions for a set of own-infra findings against the same IaC
 * discovery files the linter itself scanned. One outcome per finding, same order as `findings`.
 * Terraform only — a CFN/SAM finding (were Prompt 15 ever extended to produce one) is refused, not
 * guessed at, since there is no CFN linter here to self-check against. */
export function generatePatches(files: OwnInfraDiscoveryFile[], findings: OwnInfraFinding[]): OwnInfraFixSuggestion[] {
  const fileMap = new Map(files.filter((f) => isTerraformFile(f.path)).map((f) => [f.path, f.content]))
  const tfvars = mergeTfvars(files)
  const currentByFile = new Map(fileMap)
  const suggestions: OwnInfraFixSuggestion[] = []

  for (const finding of findings) {
    if (finding.rule === 'SINGLE_REGION' || finding.rule === 'SINGLE_INSTANCE') {
      suggestions.push({ rule: finding.rule, resource: finding.resource, file: finding.file, status: 'advisory', note: ARCHITECTURAL_NOTE[finding.rule] })
      continue
    }
    if (!PATCHABLE_RULES.includes(finding.rule)) {
      suggestions.push({ rule: finding.rule, resource: finding.resource, file: finding.file, status: 'refused', note: `Rule ${finding.rule} is not in scope for the fix generator.` })
      continue
    }
    if (!fileMap.has(finding.file)) {
      suggestions.push({
        rule: finding.rule,
        resource: finding.resource,
        file: finding.file,
        status: 'refused',
        note: 'CFN/SAM patch generation is not implemented — Prompt 15 does not parse CFN/SAM templates, so a patch here could not be self-verified by re-running the linter.',
      })
      continue
    }

    const previous = currentByFile.get(finding.file)!
    const attempt = attemptPatch(previous, finding, tfvars)
    if (attempt.status !== 'ok') {
      const status: OwnInfraFixStatus = attempt.status
      suggestions.push({ rule: finding.rule, resource: finding.resource, file: finding.file, status, note: attempt.reason })
      continue
    }

    const otherFiles = new Map([...fileMap].filter(([path]) => path !== finding.file))
    const check = selfCheck(finding.file, attempt.patchedContent, previous, otherFiles, tfvars, finding)
    if (!check.ok) {
      suggestions.push({ rule: finding.rule, resource: finding.resource, file: finding.file, status: 'refused', note: check.reason })
      continue
    }

    const diff = createTwoFilesPatch(`a/${finding.file}`, `b/${finding.file}`, previous, attempt.patchedContent)
    suggestions.push({
      rule: finding.rule,
      resource: finding.resource,
      file: finding.file,
      status: 'patched',
      diff,
      prText: buildFixPrSection(finding),
    })
    currentByFile.set(finding.file, attempt.patchedContent)
  }

  return suggestions
}
