/**
 * Writes the "Why it matters" numbers into README.md from REAL data — never hand-typed. Two
 * sources, both already real:
 *  - public/demo/documenso__documenso.json: the showcase repo's actual snapshot (same file
 *    EXAMPLE_REPOS[0] in src/data/exampleRepos.ts loads in the UI — see scripts/snapshot-repo.ts
 *    for how it's generated from a live GitHub scan).
 *  - docs/VERIFICATION.md: the real `npm test` counts, itself generated (never hand-typed) by
 *    scripts/verification-report.ts. Run that FIRST if it's stale — this script reads it as-is,
 *    it doesn't re-run the suite.
 *
 * Replaces the block between <!-- readme-numbers:start --> and <!-- readme-numbers:end --> in
 * BOTH README.md and docs/SUBMISSION.md (same block, same markers, written to whichever of the
 * two files has them) — re-run any time the showcase snapshot or VERIFICATION.md changes.
 *
 * Usage: tsx scripts/readme-numbers.ts   (also wired as `npm run readme:numbers`)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const ROOT = path.join(import.meta.dirname, '..')
const SNAPSHOT_PATH = path.join(ROOT, 'public', 'demo', 'documenso__documenso.json')
const VERIFICATION_PATH = path.join(ROOT, 'docs', 'VERIFICATION.md')
const TARGET_PATHS = [path.join(ROOT, 'README.md'), path.join(ROOT, 'docs', 'SUBMISSION.md')]

const START_MARKER = '<!-- readme-numbers:start -->'
const END_MARKER = '<!-- readme-numbers:end -->'

interface ConcentrationBySubstrate {
  substrate: string
  vendorNames: string[]
  share: number
}

interface Snapshot {
  owner: string
  repo: string
  commitSha: string
  meta: { filesScanned: number; importResolution: { total: number; resolved: number } }
  concentration: {
    vendorCount: number
    substrateCount: number
    bySubstrate: ConcentrationBySubstrate[]
    mostConcentrated: ConcentrationBySubstrate
  }
  topRecommendedMove: { vendorName: string; description: string; annualSavings: number } | null
  topRecommendedMoveWhatIf: {
    baseline: { expectedAnnualExposure: number; expectedDowntimeHoursPerYear: number }
  } | null
}

function fmtPct(n: number, digits = 0): string {
  return `${(n * 100).toFixed(digits)}%`
}

function fmtUsd(n: number): string {
  return `$${n.toLocaleString('en-US', { maximumFractionDigits: 0 })}`
}

function extractTestCountLine(verificationMd: string): string {
  // Matches the exact row scripts/verification-report.ts writes, e.g.
  // "| Full test suite | 677 tests across 67 files | ✅ 677/677 passed | `npm test` |"
  const match = /\|\s*Full test suite\s*\|\s*([^|]+)\|\s*(✅[^|]+|❌[^|]+)\|/.exec(verificationMd)
  if (!match) {
    throw new Error(
      `Could not find the "Full test suite" row in ${VERIFICATION_PATH} — run \`npm run verify:all\` first.`,
    )
  }
  return `${match[1].trim()} — ${match[2].trim()}`
}

function main() {
  const snapshot: Snapshot = JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf-8'))
  const verificationMd = readFileSync(VERIFICATION_PATH, 'utf-8')
  const testCountLine = extractTestCountLine(verificationMd)

  const { concentration, meta, topRecommendedMove, topRecommendedMoveWhatIf, owner, repo, commitSha } = snapshot
  const importResolutionPct = meta.importResolution.resolved / meta.importResolution.total

  const lines: string[] = [
    `- **${concentration.vendorCount} third-party vendors, but only ${concentration.substrateCount} independent substrates** — ` +
      `${fmtPct(concentration.mostConcentrated.share)} of vendors in [\`${owner}/${repo}\`](https://github.com/${owner}/${repo}) ` +
      `(\`${concentration.mostConcentrated.vendorNames.join(', ')}\`) share one substrate (\`${concentration.mostConcentrated.substrate}\`) — ` +
      `an outage there takes all of them down together, something no per-vendor dependency list shows.`,
    `- **${meta.filesScanned} files scanned, ${meta.importResolution.resolved}/${meta.importResolution.total} internal imports resolved (${fmtPct(importResolutionPct, 1)})** — ` +
      `the import-graph resolver's own real coverage on this repo, not a claimed number.`,
  ]

  if (topRecommendedMove && topRecommendedMoveWhatIf) {
    const { baseline } = topRecommendedMoveWhatIf
    lines.push(
      `- **One ranked mitigation, quantified**: "${topRecommendedMove.description}" is modeled to cut expected annual ` +
        `exposure by ${fmtUsd(topRecommendedMove.annualSavings)}/yr against a ${fmtUsd(baseline.expectedAnnualExposure)}/yr baseline ` +
        `(${fmtPct(topRecommendedMove.annualSavings / baseline.expectedAnnualExposure, 1)}) — under explicit, editable assumptions, never presented as a guarantee.`,
    )
  }

  lines.push(`- **${testCountLine}**, real Monte Carlo/differential/fuzz coverage — see [docs/VERIFICATION.md](docs/VERIFICATION.md).`)

  const block = [
    START_MARKER,
    `<!-- Generated by \`tsx scripts/readme-numbers.ts\` from public/demo/documenso__documenso.json (commit ${commitSha.slice(0, 7)}) and docs/VERIFICATION.md — do not hand-edit between these markers, re-run the script instead. -->`,
    ...lines,
    END_MARKER,
  ].join('\n')

  let wroteAny = false
  for (const targetPath of TARGET_PATHS) {
    const original = readFileSync(targetPath, 'utf-8')
    const startIdx = original.indexOf(START_MARKER)
    const endIdx = original.indexOf(END_MARKER)
    if (startIdx === -1 || endIdx === -1) continue // that file doesn't have the block — skip, not an error
    const updated = original.slice(0, startIdx) + block + original.slice(endIdx + END_MARKER.length)
    writeFileSync(targetPath, updated)
    console.log(`Wrote generated numbers into ${path.relative(ROOT, targetPath)}`)
    wroteAny = true
  }
  if (!wroteAny) {
    throw new Error(`Neither ${TARGET_PATHS.join(' nor ')} has ${START_MARKER} / ${END_MARKER} markers.`)
  }

  console.log('Numbers:')
  for (const line of lines) console.log(`  ${line}`)
}

main()
