/**
 * Curated demo snapshots — generated by scripts/snapshot-repo.ts from public/demo/<file>.json.
 * Numbers here are hardcoded (not fetched) so the example cards render their "N vendors -> M
 * substrates" summary with zero network calls; clicking a card fetches the actual snapshot JSON.
 *
 * Regenerate with: tsx scripts/rank-candidates.ts (to pick repos), then
 * tsx scripts/snapshot-repo.ts <owner/repo> for each — then update this file by hand from its
 * printed summary line.
 */
export interface ExampleRepo {
  owner: string
  repo: string
  /** Path under public/ — fetched relative to the site root. */
  file: string
  vendors: number
  substrates: number
  sha: string
  branch: string
  /** ISO timestamp from the snapshot's generatedAt field. */
  snapshotDate: string
  blurb: string
}

export const EXAMPLE_REPOS: ExampleRepo[] = [
  {
    owner: 'documenso',
    repo: 'documenso',
    file: '/demo/documenso__documenso.json',
    vendors: 5,
    substrates: 2,
    sha: 'e658cc5',
    branch: 'main',
    snapshotDate: '2026-09-19T03:43:37.001Z',
    blurb: 'Open-source e-signature platform — the richest vendor mix of the showcase set.',
  },
  {
    owner: 'formbricks',
    repo: 'formbricks',
    file: '/demo/formbricks__formbricks.json',
    vendors: 4,
    substrates: 2,
    sha: '357c7a2',
    branch: 'main',
    snapshotDate: '2026-09-19T03:43:48.579Z',
    blurb: 'Open-source survey platform — a real Next.js monorepo with shared infrastructure.',
  },
  {
    owner: 'nextjs',
    repo: 'saas-starter',
    file: '/demo/nextjs__saas-starter.json',
    vendors: 1,
    substrates: 1,
    sha: '6e33e58',
    branch: 'main',
    snapshotDate: '2026-09-19T03:44:01.113Z',
    blurb: 'A small, fully-scanned starter — a clean single-vendor baseline, not truncated.',
  },
]
